[build]
  publish = "build"
  functions = "functions"

[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "script-src 'self' https://raw.githubusercontent.com/cong-min/TagCloud/master/dist/TagCloud.js;"

